name: Build docker pipeline
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-24.04
    name: Build doker job

    steps:
    - uses: actions/checkout@v4.1.0

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Install all libs and dependencies
      uses: ./.github/actions/install-all-build-libs
      with:
        keytar-host-mirror: ${{ secrets.NPM_CONFIG_KEYTAR_BINARY_HOST_MIRROR }}
        sqlite3-host-mirror: ${{ secrets.NPM_CONFIG_NODE_SQLITE3_BINARY_HOST_MIRROR }}

    - name: Build sources
      run: ./.circleci/build/build.sh

    # todo: matrix
    - name: Build web archives
      run: |
        unset npm_config_keytar_binary_host_mirror
        unset npm_config_node_sqlite3_binary_host_mirror
        # Docker sources
        PLATFORM=linux ARCH=x64 LIBC=musl .circleci/build/build_modules.sh
        PLATFORM=linux ARCH=arm64 LIBC=musl .circleci/build/build_modules.sh
        # Redis Stack + VSC Linux
        PLATFORM=linux ARCH=x64 .circleci/build/build_modules.sh
        PLATFORM=linux ARCH=arm64 .circleci/build/build_modules.sh
        # VSC Darwin
        PLATFORM=darwin ARCH=x64 .circleci/build/build_modules.sh
        PLATFORM=darwin ARCH=arm64 .circleci/build/build_modules.sh
        # VSC Windows
        PLATFORM=win32 ARCH=x64 .circleci/build/build_modules.sh
    - name: Build Docker (x64, arm64)
      env:
        ENV: ${{ vars.ENV }}
        RI_SEGMENT_WRITE_KEY: ${{ secrets.RI_SEGMENT_WRITE_KEY }}
      run: |
        # Build alpine x64 image
        docker buildx build \
        -f .circleci/build/build.Dockerfile \
        --platform linux/amd64 \
        --build-arg DIST=release/web/Redis-Insight-web-linux-musl.x64.tar.gz \
        --build-arg NODE_ENV="$ENV" \
        --build-arg RI_SEGMENT_WRITE_KEY="$RI_SEGMENT_WRITE_KEY" \
        -t redisinsight:amd64 \
        .

        # Build alpine arm64 image
        docker buildx build \
        -f .circleci/build/build.Dockerfile \
        --platform linux/arm64 \
        --build-arg DIST=release/web/Redis-Insight-web-linux-musl.arm64.tar.gz \
        --build-arg NODE_ENV="$ENV" \
        --build-arg RI_SEGMENT_WRITE_KEY="$RI_SEGMENT_WRITE_KEY" \
        -t redisinsight:arm64 \
        .

        mkdir -p release/docker
        docker image save -o release/docker/docker-linux-alpine.amd64.tar redisinsight:amd64
        docker image save -o release/docker/docker-linux-alpine.arm64.tar redisinsight:arm64

    - uses: actions/upload-artifact@v4.1.0
      name: Upload docker images
      with:
        if-no-files-found: error
        name: docker
        path: ./release
