name: Tests Downloads
on:
  push:


jobs:
  upload:
    name: Upload files
    runs-on: ubuntu-latest
    steps:
      - name: 'custom file'
        run: |
          mkdir -p release
          echo "Artifact 1 content" > release/art1.txt
          echo "Artifact 2 content" > release/art2.txt
          echo "Artifact 3 content" > release/diff_name_art3.txt

      - name: 'store artifacts 1'
        uses: actions/upload-artifact@v4
        with:
          name: 'artifact'
          path: |
            release/art*

      - name: 'store artifacts 2'
        uses: actions/upload-artifact@v4
        with:
          name: 'diff'
          path: |
            release/diff*


  download-test:
    name: Download files
    needs: upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: release

      - name: Display structure of downloaded files
        run: ls -R

      - name: Zip file
        run: |
          name="artifact"
          zip -r "./release/${name}.zip" "./release/${name}"
          ls -R

